### ISSUE TITLE
config.json... Help!

### ISSUE THREAD

**Issue by jazzycamel** [Mendeley/Update-Installer#11]
I've successfully downloaded and built the tool on Mac and Windows and am now trying to create a test application with it. I have created an application on Mac which is a bundle with the following structure:

```
UpdateInstallerTestApp.app/
  - Contents/Info.plist
  - MacOS/
    - UpdateInstallerTestApp
  - PkgInfo
  - Resources/
    - empty.lproj
```

How would I go about composing a config.json file to represent this as I have tried quite a number of versions now and can't get anything to run, for example:

```
{
    "packages" : {
        "app" : [".*"]
    },
   
    "updater-binary" : "updater",

    "main-binary" : "UpdateInstallerTestApp.app"
}
```

yields the following error:

```
Generating package app
	zip warning: name not matched: /UpdateInstallerTestApp.app

zip error: Nothing to do! (/Users/rob/Documents/Qt5/UpdateInstallerTestApp/build/output/app.zip)
/Users/rob/Update-Installer/tools/create-packages.rb:375:in `block (2 levels) in <main>': Failed to generate package app (RuntimeError)
	from /Users/rob/Update-Installer/tools/create-packages.rb:373:in `chdir'
	from /Users/rob/Update-Installer/tools/create-packages.rb:373:in `block in <main>'
	from /Users/rob/Update-Installer/tools/create-packages.rb:333:in `each'
	from /Users/rob/Update-Installer/tools/create-packages.rb:333:in `<main>'
```

And no matter what I do with the `packages` section I can't make it happy! I appreciate I'm probably being immensely dense here, but some help for a newbie would be greatly appreciated.

Thanks a lot :)

**Comment by suy** [comment]
`main-binary` seems to be the main executable in the bundle, which would typically be the one in `Contents/MacOS`. Just use the name inside that directory.
